using System.ComponentModel.DataAnnotations;

namespace Spellfire.Model
{
    public enum CharacteristicKey : byte
    {
        [Display(Name = "Adventurer")]
        Adventurer = 101,
        [Display(Name = "Avatar")]
        Avatar = 102,
        [Display(Name = "Awnshegh")]
        Awnshegh = 103,
        [Display(Name = "Beholder")]
        Beholder = 104,
        [Display(Name = "Black Wizard")]
        BlackWizard = 105,
        [Display(Name = "Champion")]
        Champion = 106,
        [Display(Name = "Coastal")]
        Coastal = 107,
        [Display(Name = "Defensive")]
        Defensive = 108,
        [Display(Name = "Draconian")]
        Draconian = 109,
        [Display(Name = "Dragon")]
        Dragon = 110,
        [Display(Name = "Dragon Unarmed Combat")]
        DragonUnarmedCombat = 111,
        [Display(Name = "Drow")]
        Drow = 112,
        [Display(Name = "Duergar")]
        Duergar = 113,
        [Display(Name = "Dwarf")]
        Dwarf = 114,
        [Display(Name = "Earthwalker")]
        Earthwalker = 115,
        [Display(Name = "Elf")]
        Elf = 116,
        [Display(Name = "Familiar")]
        Familiar = 117,
        [Display(Name = "Flyer")]
        Flyer = 118,
        [Display(Name = "Giant")]
        Giant = 119,
        [Display(Name = "Gnome")]
        Gnome = 120,
        [Display(Name = "Golem")]
        Golem = 121,
        [Display(Name = "Half-Elf")]
        HalfElf = 122,
        [Display(Name = "Halfling")]
        Halfling = 123,
        [Display(Name = "Harmful")]
        Harmful = 124,
        [Display(Name = "Helpful")]
        Helpful = 125,
        [Display(Name = "Kender")]
        Kender = 126,
        [Display(Name = "Kobold")]
        Kobold = 127,
        [Display(Name = "Mul")]
        Mul = 128,
        [Display(Name = "Offensive")]
        Offensive = 129,
        [Display(Name = "Orc")]
        Orc = 130,
        [Display(Name = "Red Wizard")]
        RedWizard = 131,
        [Display(Name = "Spear")]
        Spear = 132,
        [Display(Name = "Svirfneblin")]
        Svirfneblin = 133,
        [Display(Name = "Swimmer")]
        Swimmer = 134,
        [Display(Name = "Sword")]
        Sword = 135,
        [Display(Name = "Undead")]
        Undead = 136,
        [Display(Name = "Undead Unarmed Combat")]
        UndeadUnarmedCombat = 137,
        [Display(Name = "Underdark")]
        Underdark = 138,
        [Display(Name = "Use Blood Ability")]
        UseBloodAbility = 139,
        [Display(Name = "Use Cleric Spell")]
        UseClericSpell = 140,
        [Display(Name = "Use Dragon Unarmed Combat")]
        UseDragonUnarmedCombat = 141,
        [Display(Name = "Use Psionic Power")]
        UsePsionicPower = 142,
        [Display(Name = "Use Thief Skill")]
        UseThiefSkill = 143,
        [Display(Name = "Use Unarmed Combat")]
        UseUnarmedCombat = 144,
        [Display(Name = "Use Undead Unarmed Combat")]
        UseUndeadUnarmedCombat = 145,
        [Display(Name = "Use Wizard Spell")]
        UseWizardSpell = 146,
        [Display(Name = "Vampire")]
        Vampire = 147,
        [Display(Name = "Weapon")]
        Weapon = 148,
        [Display(Name = "Werebeast")]
        Werebeast = 149,
        [Display(Name = "White Wizard")]
        WhiteWizard = 150
    }
}

